<?php

/**
 * Чистит логи менеджеров старше 2-х месяцев
 */
class CrontabControllerSupportClearLogManager extends modCrontabController
{
    public $classKey = 'modManagerLog';
    protected function prepareListQueryBeforeCount(xPDOQuery $c)
    {
        $today = date('Y-m-d', strtotime('-60 days', time()));
        $c->where([
            'occurred:<' => $today
        ]);
        return parent::prepareListQueryBeforeCount($c); // TODO: Change the autogenerated stub
    }

    protected function prepare($object)
    {
        $object->remove();
    }
}
